### ISSUE TITLE
gem install libv8 -v '3.16.14.7' fails on OS X 10.10.3

### ISSUE THREAD

**Issue by jezcaudle** [cowboyd/libv8#171]
Hi,

I'm trying to:

gem install libv8 -v '3.16.14.7'

so I can get the RubyRacer working on OS X 10.10.3

Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 6.1.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/jezcaudle/.rvm/gems/ruby-2.1.1@rails4.2.1/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:33:
In file included from ../src/heap.h:35:
In file included from ../src/incremental-marking.h:33:
In file included from ../src/mark-compact.h:32:
../src/spaces.h:896:26: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  bool exists() { return this != NULL && code_range_ != NULL; }
                         ^~~~    ~~~~
../src/spaces.h:898:9: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]
    if (this == NULL || code_range_ == NULL) return false;
        ^~~~    ~~~~
2 errors generated.

Xcode is 6.3.2

ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]

It did work perfectly with:

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

So feel free to delete this!!

**Comment by cowboyd** [comment]
You should be able to recompile ruby 2.1.1 which looks like it was compiled on Mountain Lion(darwin-12). I don't believe there is a binary gem for this version.
