### PR TITLE
Add patch to allow build with clang 7.3

### PR DESCRIPTION
**Pull request by aviat**
This adds the -Wno-shift-negative-value flag to Clang. Clang 7.3 was introduced
in OSX with XCode 7.3.

Without this flag, compiling with Clang 7.3 fails with errors such as:

    In file included from ../src/elements.h:32:
    ../src/objects.h:5252:44: error: shifting a negative signed value is undefined
    [-Werror,-Wshift-negative-value]
      static const int kElementsKindMask = (-1 << kElementsKindShift) &
                                            ~~ ^
    ../src/objects.h:7386:36: error: shifting a negative signed value is undefined
    [-Werror,-Wshift-negative-value]
          (~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    2 errors generated.

### CODE REVIEW

**Comment by aviat** [comment]
This should resolve #205, as well as:
-  https://github.com/cowboyd/therubyracer/issues/405
 - https://github.com/cowboyd/therubyracer/issues/403

**Comment by julik** [comment]
@cowboyd it would be great if this could be merged, I already had to `install_if` on 3 projects that use libv8 indirectly (I know it is a +1 comment at heart and I will be punished, and yet hope dies last).

**Comment by ignisf** [comment]
Thank you for the contribution!

**Comment by aviat** [comment]
You are welcome @ignisf. Any idea when the new gem could be published?

**Comment by ignisf** [comment]
I usually leave releasing the gem to @cowboyd, as I have no way of producing osx binaries and it's a bad idea to leave all osx users to deal with the touchy build process of v8. So... No, no idea :confused:...

**Comment by aviat** [comment]
@ignisf I could give you the darwin14 / darwin15 builds if that helps!

**Comment by ignisf** [comment]
Thank you, but I would not publish binaries made on a system I can't trust.

**Comment by aviat** [comment]
Which is a relief for all of us :)
So let's wait for @cowboyd.
