### PR TITLE
Add patch for clang 7.3 (-Wshift-negative-value)

### LINKED ISSUE #205: libv8 fails to compile with OS X 10.11.4/Xcode 7.3/clang 7.3.0
````
Installing libv8 3.16.14.13 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/ext/libv8
/Users/tmorgan/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160321-41246-m0y5mf.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.10
Using compiler: /usr/bin/c++ (clang version 7.3.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:32:
../src/objects.h:5252:44: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
  static const int kElementsKindMask = (-1 << kElementsKindShift) &
                                        ~~ ^
../src/objects.h:7386:36: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
      (~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.
make[1]: *** [/Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make: *** [x64.release] Error 2
/Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `each'
	from /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  LIBTOOL-STATIC /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/libpreparser_lib.a
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/preparser
  CXX(target) /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o

extconf failed, exit code 1

Gem files will remain installed in /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/gems/libv8-3.16.14.13 for inspection.
Results logged to /Users/tmorgan/.rvm/gems/ruby-2.3.0@squash/extensions/x86_64-darwin-15/2.3.0/libv8-3.16.14.13/gem_make.out
````

### PR DESCRIPTION
**Pull request by burke**
This fixes gem install for me on OS X 10.11.4, XCode 7.3, clang 7.3.

Resolves #205

### CODE REVIEW

**Comment by aviat** [comment]
@burke I saw your PR a bit late after I made #207 - basically the same thing, but patching options passed to clang, disabling `-Wshift-negative-value`, instead of patching V8. It seems simpler and more reliable to me. Furthremore, similar issues was already handled in this way (check all the `clang*` directories under `libv8/patches`).
What do you think about that?

**Comment by ignisf** [comment]
This should no longer be necessary due to #207 being merged. Please test.
