### ISSUE TITLE
Repeatedly failing to install on Mavericks…

### ISSUE THREAD

**Issue by skipchris** [cowboyd/libv8#120]
Hey,

First up, a couple of caveats/apologies:

1) Sorry if this isn’t the best way/right place to get help - but the README doesn’t make anywhere else clear, so I thought I’d give this a shot as I’ve been stuck for days.
2) Sorry if this isn’t a libv8 problem, but again, I’ve no idea where else to turn. If you can even point me in the right direction, I’d be grateful.
3) I’m not looking for someone to sort my life out for me – if you can even suggest some lines of inquiry which might help me out, I’m willing to pursue them, because right now I’m out of ideas.

Basically, I can’t install libv8 (and consequently therubyracer) via bundler on OS X 10.9. I’ve tried lots of different approaches, and nothing seems to work. I’ve been running 10.9 for a while and not seen any problems, but this may be the first time I’ve needed to install libv8 since upgrading, my memory isn’t clear.

I documented the problem pretty comprehensively on Stack Overflow a couple of days ago, but no-one’s been able to help:

https://stackoverflow.com/questions/22481435/fix-therubyracer-libv8-0-12-1-installation-on-mavericks

If you’d like me to reproduce the description here or add any more details, not a problem, just let me know what you need.

Thanks,
Chris.

**Comment by alexey** [comment]
I had similar problem leading to therubyracer installation fail.

I solved it with:
```
sudo ln -s /Library/Developer/CommandLineTools/usr/bin/cpp /usr/bin/cpp
sudo ln -s /Library/Developer/CommandLineTools/usr/bin/gcc /usr/bin/gcc
sudo ln -s /Library/Developer/CommandLineTools/usr/bin/g++ /usr/bin/g++
brew uninstall v8
gem install libv8
gem install therubyracer
```

From here:

**Comment by ksarna** [comment]
Tried everything: reinstalling rubies, nuking rvm, brew v8, --with-system-v8, cloning libv8 and trying to run rake install, downgrading command line tools to 6.2. Nothing helped. Luckily a version 6.4 of xcode arrived and bundle install just worked. \***sigh**\*

**Comment by cowboyd** [comment]
@ksarna The biggest problem was that developers on OSX should never have to compile libv8 ever because there is a [binary gem for mavericks][2]. It turned out to be [an issue with rubygems], where a binary gem built with rubygems < 2.2 would not be selected by rubygems > 2.4.

The 6.4 commandline tools are still incompatible with the version of v8 we use, but last night I released a new binary gem build with rubygems 2.4.2 which is selected correctly.

Hopefully this resolves further issues.

[1]: https://github.com/rubygems/rubygems/issues/1299
[2]: https://rubygems.org/gems/libv8/versions/3.16.14.11-x86_64-darwin-14

**Comment by ksarna** [comment]
@cowboyd sounds good! Thanks for the info and your work.

**Comment by JikkuJose** [comment]
@calexicoz exactly the same issue here! 

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/jikkujose/.gem/ruby/2.2.2/extensions/x86_64-darwin-15/2.2.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/jikkujose/.gem/ruby/2.2.2/extensions/x86_64-darwin-15/2.2.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace
```

This is what I did, before starting the server.

```
brew install v8
gem install libv8 -v '3.16.14.7' -- --with-system-v8
gem install therubyracer -v '0.12.2' -- --with-system-v8
```

System config:
El Capitan
Ruby: 2.2.2

Any more information is required?

**Comment by Vorob-Astronaut** [comment]
+1

**Comment by warp-linden** [comment]
@JikkuJose Same issue here

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/warp/development/opensource/rails-loaded/vendor/ruby/2.1.0/extensions/x86_64-darwin-15/2.1.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/warp/development/opensource/rails-loaded/vendor/ruby/2.1.0/extensions/x86_64-darwin-15/2.1.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```
