### ISSUE TITLE
Fails to build on macOS High Sierra with ruby 2.1.2

### ISSUE THREAD

**Issue by anikolaev94** [cowboyd/libv8#252]
I've got `therubyracer` gem in my Rails project, that depends on `libv8`. Any time I run `bundle install` on command line, it fails with the following:

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/bakahakka/.rbenv/versions/2.1.2/bin/ruby extconf.rb
    creating Makefile
    Compiling v8 for x64
    Using python 2.7.10
    Using compiler: /usr/bin/c++ (clang version 9.0.0)
    ../src/bignum.cc:761:7: error: variable 'i' is incremented both in the loop header and in the loop 
    body
    [-Werror,-Wfor-loop-analysis]
        ++i;
          ^
    ../src/bignum.cc:756:72: note: incremented here
      for (int i = other.used_digits_ + exponent_diff; i < used_digits_; ++i) {
                                                                       ^
    1 error generated. 
    make[1]: ***
    [/Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o]
    Error 1
    make: *** [x64.release] Error 2
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/ext/libv8/location.rb:36:in `block in
    verify_installation!': libv8 did not install properly, expected binary v8 archive
    '/Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to
    exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/ext/libv8/location.rb:35:in `each'
    from /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/ext/libv8/location.rb:35:in
    `verify_installation!'
        from /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'
    GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=x64 \
    -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2
    -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
    CXX(target)
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
    CXX(target)
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    
    3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
    CXX(target)
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-
    3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o

    extconf failed, exit code 1

    Gem files will remain installed in 
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/libv8-3.16.14.7 for
    inspection.
    Results logged to
    /Users/bakahakka/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-17/2.1.0-static/libv8-3.16.14.7/gem_make.out

    An error occurred while installing libv8 (3.16.14.7), and Bundler cannot continue.
    Make sure that `gem install libv8 -v '3.16.14.7'` succeeds before bundling.
